/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package praxis.guilego;
import java.awt.event.KeyEvent;
import praxis.OrderEntryListener;
import javax.swing.*;

/**
 *
 * @author andsmith
 */
public class OrderEntryFrame extends javax.swing.JFrame {


    final OrderEntryListener listener;

    /**
     * Creates new form frmOrderEntry
     */
    public OrderEntryFrame(OrderEntryListener lis) {
        initComponents();
        this.listener = lis;
    }

    public OrderEntryFrame( ) {
        this(new OrderEntryListener() {

            @Override
            public void onEntryString(String s) {
                System.out.println("Beep boop" + s);
            }


            @Override
            public void onButtonPress(String s) {
                  System.out.println("Fire in the hole " + s);
            }
        } );
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtOrderEntry = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtRic = new javax.swing.JTextField();
        txtSide = new javax.swing.JTextField();
        cmdSend = new javax.swing.JButton();
        txtQty = new javax.swing.JTextField();
        txtDest = new javax.swing.JTextField();
        lblDescription = new javax.swing.JLabel();
        lblDailyID = new javax.swing.JLabel();
        txtBB = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtGlobalId = new javax.swing.JLabel();
        txtGlobalID = new javax.swing.JTextField();
        txtDailyID2 = new javax.swing.JLabel();
        txtDailyID3 = new javax.swing.JLabel();
        txtDailyID4 = new javax.swing.JLabel();
        txtDailyID5 = new javax.swing.JLabel();
        txtMicroStrategy = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtInstructions = new javax.swing.JTextArea();

        txtOrderEntry.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        txtOrderEntry.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtOrderEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderEntryActionPerformed(evt);
            }
        });
        txtOrderEntry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOrderEntryKeyPressed(evt);
            }
        });

        jLabel5.setText("RIC");

        jLabel6.setText("SIDE");

        jLabel7.setText("QTY");

        jLabel8.setText("DEST");

        txtRic.setEditable(false);

        txtSide.setEditable(false);

        cmdSend.setText("SEND");
        cmdSend.setEnabled(false);
        cmdSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSendActionPerformed(evt);
            }
        });

        txtQty.setEditable(false);

        txtDest.setEditable(false);

        lblDescription.setText("desc");

        lblDailyID.setText("BB");

        txtBB.setEditable(false);
        txtBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBBActionPerformed(evt);
            }
        });

        txtGlobalId.setText("GLOBALID");

        txtGlobalID.setEditable(false);

        txtDailyID5.setText("USTRAT");

        txtMicroStrategy.setEditable(false);

        txtInstructions.setEditable(false);
        txtInstructions.setBackground(new java.awt.Color(0, 0, 0));
        txtInstructions.setColumns(20);
        txtInstructions.setFont(new java.awt.Font("Lucida Console", 0, 10)); // NOI18N
        txtInstructions.setForeground(new java.awt.Color(153, 255, 153));
        txtInstructions.setRows(5);
        txtInstructions.setSelectionColor(new java.awt.Color(204, 204, 255));
        jScrollPane2.setViewportView(txtInstructions);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(cmdSend)
                .addGap(18, 18, 18)
                .addComponent(lblDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtOrderEntry)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSide, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDest, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDailyID4)
                                    .addComponent(txtDailyID2)
                                    .addComponent(txtDailyID3))
                                .addGap(251, 251, 251))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGlobalId)
                                    .addComponent(txtDailyID5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMicroStrategy, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGlobalID, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(392, 392, 392))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtRic, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDailyID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBB, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtOrderEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDailyID)
                    .addComponent(txtBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGlobalId)
                    .addComponent(txtGlobalID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDailyID5)
                    .addComponent(txtMicroStrategy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDailyID2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDailyID3)
                        .addGap(26, 26, 26)
                        .addComponent(txtDailyID4))
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdSend)
                    .addComponent(lblDescription))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtOrderEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderEntryActionPerformed
        // TODO add your handling code here:
        listener.onEntryString( txtOrderEntry.getText());
     //   if (evt.)

    }//GEN-LAST:event_txtOrderEntryActionPerformed

    private void txtOrderEntryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOrderEntryKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() != KeyEvent.VK_ENTER) {
            //cmdSend.setEnabled(false);
        }
        
        
        //if (evt.is)
//        if (true || evt.getKeyCode()==  KeyEvent.VK_ENTER) {
//            //log.info("Woot got an enter")
//            listener.onEntryString(txtOrderEntry.getText());
//        }
    }//GEN-LAST:event_txtOrderEntryKeyPressed

    private void cmdSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSendActionPerformed
       //cmdSend.setEnabled(false);
       listener.onButtonPress(txtOrderEntry.getText());
    }//GEN-LAST:event_cmdSendActionPerformed

    private void txtBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, UnsupportedLookAndFeelException, InstantiationException, IllegalAccessException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderEntryFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cmdSend;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDailyID;
    public javax.swing.JLabel lblDescription;
    public javax.swing.JTextField txtBB;
    private javax.swing.JLabel txtDailyID2;
    private javax.swing.JLabel txtDailyID3;
    private javax.swing.JLabel txtDailyID4;
    private javax.swing.JLabel txtDailyID5;
    public javax.swing.JTextField txtDest;
    public javax.swing.JTextField txtGlobalID;
    private javax.swing.JLabel txtGlobalId;
    public javax.swing.JTextArea txtInstructions;
    public javax.swing.JTextField txtMicroStrategy;
    private javax.swing.JTextField txtOrderEntry;
    public javax.swing.JTextField txtQty;
    public javax.swing.JTextField txtRic;
    public javax.swing.JTextField txtSide;
    // End of variables declaration//GEN-END:variables
}
